--KH_연습문제
--1. 70년대 생(1970~1979) 중 여자이면서 전씨인 사원의 이름과 주민번호, 부서 명, 직급 조회
SELECT EMP_NAME, EMP_NO
FROM EMPLOYEE
WHERE EMP_NAME LIKE '전%' AND SUBSTR(EMP_NO,8,1)='2';

SELECT EMP_NAME, EMP_NO,DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_TITLE = (SELECT EMP_NAME, EMP_NO
                    FROM EMPLOYEE
                    WHERE EMP_NAME LIKE '전%' AND SUBSTR(EMP_NO,8,1)='2');



--2. 나이 상 가장 막내의 사원 코드, 사원 명, 나이, 부서 명, 직급 명 조회


SELECT *
FROM EMPLOYEE;

EMP_ID, EMP_NAME, EMO_NO, 

SELECT *
FROM DEPARTMENT;
DEPT_TITLE, 

SELECT *
FROM JOB;
JOB_NAME

--3. 이름에 ‘형’이 들어가는 사원의 사원 코드, 사원 명, 직급 조회(성공)

SELECT EMP_ID, EMP_NAME,JOB_NAME
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE
AND EMP_NAME LIKE '_형_';


SELECT *
FROM EMPLOYEE; --JOB_CODE

SELECT *
FROM JOB; --JOB_CODE
--사원 코드 : EMP_ID, 직급 : JOB_CODE

--4. 부서코드(DEPT_ID)가 D5이거나 D6인 사원의 사원 명, 직급 명(JOB_NAME), 부서 코드, 부서 명(DEPT_TITLE) 조회
SELECT EMP_NAME ,JOB_NAME, DEPT_ID, DEPT_TITLE
FROM EMPLOYEE E, JOB J,DEPARTMENT D
WHERE E.JOB_CODE = J.JOB_CODE
AND DEPT_CODE = DEPT_ID
AND DEPT_ID ='D5' OR DEPT_ID = 'D6';


SELECT *
FROM EMPLOYEE;--JOB_CODE  --DEPT_CODE

SELECT *
FROM JOB; --JOB_CODE

SELECT *
FROM DEPARTMENT;    --DEPT_ID

SELECT *
FROM NATIONAL;
--5. 보너스를 받는 사원의 사원 명, 부서 명, 지역 명 조회 (성공)
SELECT BONUS
FROM EMPLOYEE
WHERE BONUS IS NOT NULL;


SELECT EMP_NAME,BONUS, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE, DEPARTMENT, LOCATION
WHERE DEPT_CODE = DEPT_ID
AND LOCATION_ID = LOCAL_CODE
AND BONUS IS NOT NULL;


SELECT *
FROM EMPLOYEE;--DEPT_CODE

SELECT *
FROM JOB;

SELECT *
FROM DEPARTMENT;   --DEPT_ID        --LOCATION_ID 

SELECT *
FROM LOCATION;                       --LOCAL_CODE


--6. 사원 명, 직급 명, 부서 명, 지역 명 조회(성공)
SELECT * FROM EMPLOYEE;     --JOB_CODE     --DEPT_CODE
SELECT * FROM JOB;          --JOB_CODE
SELECT * FROM DEPARTMENT;               --DEPT_ID                      --LOCATION_ID
SELECT * FROM LOCATION;                                        --LOCAL_CODE

SELECT EMP_NAME, JOB_NAME, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE E, JOB J, DEPARTMENT, LOCATION
WHERE E.JOB_CODE = J.JOB_CODE
AND DEPT_CODE=DEPT_ID
AND LOCATION_ID = LOCAL_CODE;



--7. 한국이나 일본에서 근무 중인 사원의 사원 명, 부서 명, 지역 명, 국가 명 조회
SELECT* FROM EMPLOYEE;    -- DEPT_CODE
SELECT* FROM DEPARTMENT; --DEPT_ID      --LOCATION_ID
SELECT* FROM LOCATION;                  --LOCAL_CODE      --NATIONAL_CODE  
SELECT* FROM NATIONAL;                                     --NATIONAL_CODE

SELECT EMP_NAME, DEPT_TITLE, LOCAL_NAME, NATIONAL_NAME
FROM EMPLOYEE,DEPARTMENT,LOCATION L,NATIONAL N
WHERE DEPT_CODE = DEPT_ID
AND LOCATION_ID = LOCAL_CODE
AND LOCAL_NAME = 'ASIA1' OR LOCAL_NAME = 'ASIA2'
AND L.NATIONAL_CODE = N.NATIONAL_CODE
AND N.NATIONAL_NAME = '한국' OR N.NATIONAL_NAME = '일본';


--8. 한 사원과 같은 부서에서 일하는 사원의 이름 조회
SELECT EMP_NAME,DEPT_CODE
FROM EMPLOYEE,DEPARTMENT
WHERE DEPT_CODE = DEPT_ID;

SELECT EMP_NAME
FROM EMPLOYEE;


SELECT * FROM EMPLOYEE; --DEPT_CODE
SELECT * FROM DEPARTMENT; --DEPT_ID


--9. 보너스가 없고 직급 코드가 J4이거나 J7인 사원의 이름, 직급 명(JOB_NAME), 급여 조회(NVL 이용)
SELECT *
FROM EMPLOYEE;--JOB_CODE

SELECT *
FROM JOB;--JOB_CODE

SELECT EMP_NAME, JOB_NAME, SALARY
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE;


--10. 보너스 포함한 연봉이 높은 5명의 사번, 이름, 부서 명, 직급, 입사일, 순위 조회
SELECT *
FROM EMPLOYEE;      --EMP_ID,EMP_NAME,HIRE_DATE         --DEPT_CODE         --JOB_CODE

SELECT *
FROM DEPARTMENT;        --DEPT_TITLE                    --DEPT_ID               

SELECT *
FROM JOB;   -- JOB_NAME                                                     -JOB_NAM

--연봉 => (SALARY + SALARY*BONUS)*12

SELECT EMP_ID,EMP_NAME
FROM EMPLOYEE
ORDER BY (SALARY + SALARY*BONUS)*12;


SELECT EMP_ID,EMP_NAME, 



--11. 부서 별 급여 합계가 전체 급여 총 합의 20%보다 많은 부서의 부서 명, 부서 별 급여 합계 조회
--11-1. JOIN과 HAVING 사용





--11-2. 인라인 뷰 사용





--12. 부서 명과 부서 별 급여 합계 조회


