--1번 문제
SELECT DEPARTMENT_NAME AS"학과 명" ,CATEGORY AS"계열"
FROM TB_DEPARTMENT;

--2번 문제
SELECT DEPARTMENT_NAME||'의 정원은 '|| CAPACITY || '명 입니다.'
FROM TB_DEPARTMENT;

--3번 문제
SELECT STUDENT_NAME 
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'AND SUBSTR(STUDENT_SSN,8,1)=2 AND DEPARTMENT_NO =001;

--4번 문제
SELECT STUDENT_NAME
FROM  TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NO DESC;

--5번
SELECT DEPARTMENT_NAME,CATEGORY 
FROM TB_DEPARTMENT
WHERE CAPACITY >=20 AND CAPACITY <=30;

--6번
SELECT PROFESSOR_NAME 
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--7번
SELECT DEPARTMENT_NO ,STUDENT_NAME 
FROM  TB_STUDENT
WHERE  DEPARTMENT_NO IS NULL;

--8번
SELECT CLASS_NO 
FROM TB_CLASS
WHERE  PREATTENDING_CLASS_NO IS NOT NULL;

--9번
SELECT DISTINCT(CATEGORY)
FROM TB_DEPARTMENT
ORDER BY CATEGORY;

--10번
SELECT STUDENT_NO,STUDENT_NAME,STUDENT_SSN 
FROM TB_STUDENT
WHERE ABSENCE_YN = 'N' AND SUBSTR(STUDENT_NO,2,1) = 2 AND SUBSTR(STUDENT_ADDRESS,1,2)='전주';

--함수

--1번 
SELECT STUDENT_NO AS"학번" ,STUDENT_NAME AS"이름", ENTRANCE_DATE AS"입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

--2번 이름 글자수
SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME)!='3'; 

--3번(1948년 해결하기)
SELECT PROFESSOR_NAME AS "교수이름",
FLOOR(MONTHS_BETWEEN(SYSDATE,TO_DATE(SUBSTR(PROFESSOR_SSN,1,6)))/12)
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1)='1'
ORDER BY PROFESSOR_SSN DESC;

--4번
SELECT SUBSTR(PROFESSOR_NAME,2,2) AS "이름"
FROM TB_PROFESSOR;

--5번
SELECT STUDENT_NO,STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,2,1)=SUBSTR(STUDENT_SSN,2,1);

--6번
SELECT TO_CHAR(TO_DATE('20201225','YYMMDD'),'DAY')
FROM DUAL;

--7번
SELECT TO_DATE('99/10/11','YY/MM/DD')
FROM DUAL;

SELECT TO_DATE('49/10/11','YY/MM/DD') 
FROM DUAL;

SELECT TO_DATE('99/10/11','RR/MM/DD')
FROM DUAL;

SELECT TO_DATE('49/10/11','RR/MM/DD')
FROM DUAL;

--8번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';

--9번 
SELECT ROUND(AVG(POINT),1) AS"평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178' ;

--10번 (학생수가 틀림)
SELECT DEPARTMENT_NO AS "학과 번호", COUNT(*) AS"학생수(명)"
FROM TB_CLASS
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--11번
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS  NULL;


--12번
SELECT SUBSTR(TERM_NO,1,4), ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 1;

--13번 휴학생이 없는 과 존재
SELECT DEPARTMENT_NO AS "학과 번호",COUNT(ABSENCE_YN)
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY 1;


--14번
SELECT STUDENT_NAME, COUNT(STUDENT_NAME)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) >1;

--15번(년도 별 누적 평점, 총평점)
SELECT SUBSTR(TERM_NO,1,4)AS"년도",SUBSTR(TERM_NO,5,2)AS"학기",POINT
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113';


--OPTION
--1번
SELECT STUDENT_NAME,STUDENT_ADDRESS 
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

--2번
SELECT STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

--3번
SELECT STUDENT_NAME AS "학생이름",STUDENT_NO AS "학번",STUDENT_ADDRESS AS"거주지 주소"
FROM TB_STUDENT
WHERE (SUBSTR(STUDENT_ADDRESS,1,2)='강원' OR SUBSTR(STUDENT_ADDRESS,1,2)='경기')AND SUBSTR(STUDENT_NO,1,1)='9'
ORDER BY STUDENT_NAME;

--4번
SELECT PROFESSOR_NAME ,PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO=005
ORDER BY PROFESSOR_SSN;

--5번(소수점 표현)
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE SUBSTR(TERM_NO,1,4)=2004 AND SUBSTR(TERM_NO,5,2)=02 AND CLASS_NO='C3118100'
ORDER BY POINT DESC, STUDENT_NO;

--6번 
SELECT STUDENT_NO,STUDENT_NAME,DEPARTMENT_NAME
FROM TB_STUDENT S,TB_DEPARTMENT D
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO; 

--7번 
SELECT CLASS_NAME,DEPARTMENT_NAME
FROM TB_CLASS C,TB_DEPARTMENT D
WHERE C.DEPARTMENT_NO = D.DEPARTMENT_NO;

--8번 다시
SELECT DISTINCT C.CLASS_NAME,P.PROFESSOR_NAME
FROM TB_CLASS C,TB_PROFESSOR P
WHERE C.DEPARTMENT_NO = P.DEPARTMENT_NO
ORDER BY PROFESSOR_NAME;

SELECT *
FROM TB_CLASS
WHERE CLASS_NAME = '발레워크샵';

SELECT *
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME ='강용진';
ORDER BY DEPARTMENT_NO DESC;

--9번




--10번
SELECT STUDENT_NO,STUDENT_NAME,POINT
FROM TB_STUDENT,TB_GRADE
WHERE ;





SELECT *
FROM TB_DEPARTMENT;

SELECT *
FROM TB_GRADE;






--11번






--12번 다시
SELECT STUDENT_NAME,TERM_NO,CLASS_NAME
FROM TB_STUDENT,TB_GRADE,TB_CLASS
WHERE SUBSTR(TERM_NO,1,4)=2007 AND CLASS_NAME = '인간관계론';

--13번

--14번

--15번

--16번

--17번

--18번

--19번














